### ISSUE TITLE
Failure to build certain versions

### ISSUE THREAD

**Issue by ndmitchell** [digital-asset/ghc-lib#129]
https://matrix.hackage.haskell.org/#/package/ghc-lib-parser/ has some red boxes. You can eliminate those red boxes by constraining some bounds. They suggest that the GHC HEAD things you are doing have broken GHC 8.8.

**Comment by hurryabit** [comment]
@shayne-fletcher-da That looks like one for you to drive.

**Comment by cocreature** [comment]
This is an issue in GHC itself: You are currently unable to build GHC HEAD with GHC 8.8. I’ve opened a PR for the issue experienced in ghc-lib https://gitlab.haskell.org/ghc/ghc/merge_requests/1662 but there are other issues as well, see https://gitlab.haskell.org/ghc/ghc/issues/16797 and https://gitlab.haskell.org/ghc/ghc/issues/17146.

In the meantime the only thing we can do is to constrain bounds such that there is no install plan for 8.8 for ghc-lib HEAD.

**Comment by shayne-fletcher-da** [comment]
@cocreature 's MR https://gitlab.haskell.org/ghc/ghc/merge_requests/1662 definitely fixes the problem for `ghc-lib-parser`. Checking now if we are going to run foul of the other problems building `ghc-lib` itself.

**Comment by shayne-fletcher-da** [comment]
`ghc-lib` dodges a bullet and is unaffected by the other ghc issues. @cocreature 's MR has been accepted - as soon as it lands, I'll cut a new release.

**Comment by shayne-fletcher-da** [comment]
[Commit landed](https://gitlab.haskell.org/ghc/ghc/commit/d0b45ac6984f245bce9de7ffcc7dad4a0046d344). Release ghc-lib-0.20190909 out the door.
