### ISSUE TITLE
Check our GHC_STAGE handling

### ISSUE THREAD

**Issue by shayne-fletcher-da** [digital-asset/ghc-lib#149]
This ghc [commit](https://gitlab.haskell.org/ghc/ghc/commit/817c1a947d50a070613815e02a530f83d9078eb8) does a bit more than rename the manifest constant `STAGE` to `GHC_STAGE` - it looks like it sets the constant in `ghc_platform.h` rather than from the command line.

We have two things to consider in ghc-lib-gen : `applyPatchStage` (probably fine) and whether we should be passing `-DGHC_STAGE` to the `cpp-options` in the ghc-lib-parser and ghc-lib cabal files. I suspect not because I'm seeing lots of warnings like this:
```
ghc-lib> /Users/shaynefletcher/tmp/ghc-lib/ghc-lib/ghc-lib/stage0/lib/ghcplatform.h:4:9: error:
ghc-lib>      warning: 'GHC_STAGE' macro redefined [-Wmacro-redefined]
ghc-lib>   |
ghc-lib> 4 | #define GHC_STAGE 1
ghc-lib>   |         ^
ghc-lib> #define GHC_STAGE 1
```

**Comment by cocreature** [comment]
> This ghc [commit](https://gitlab.haskell.org/ghc/ghc/commit/817c1a947d50a070613815e02a530f83d9078eb8) does a bit more than rename the manifest constant `STAGE` to `GHC_STAGE`

It doesn’t seem to do that at all, that’s part of a separate commit https://gitlab.haskell.org/ghc/ghc/commit/0c0a15a8541a9119536ee17849d8390cb21ab764.

As for the CPP define, we definitely shouldn’t set that anymore. We either need to check that the way it’s defined in `ghcplatform.h` is fine with all `#if` guards (we patch out some that were problematic in the past but there are probably others) in `ghc-lib`, patch `ghcplatform.h` to set it to something different if that fixes the `#if` guards or patch out all of the remaining guards to whatever we want them to be.

**Comment by shayne-fletcher-da** [comment]
On master, `ghcplatform.h` sets `GHC_STAGE = 1` and we no longer are required to pass pass `-DGHC_STAGE=2` to `cpp-options` to get a successful build. All usages of `getOrSetLibHSghc*` require `GHC_STAGE >= 2`. So, it looks like we are no longer required to `applyPatchStage` on master and can drop the `-DGHC_STAGE=2` from the cabal files.
