### ISSUE TITLE
Hidden by default

### ISSUE THREAD

**Issue by vaibhavsagar** [digital-asset/ghc-lib#158]
The README states that `ghc-lib` and `ghc-lib-parser` are currently not hidden by default because this requires newer versions of Cabal. Can this decision be revisited, now that `cabal-install` 3.0.0.0 is widely used?

**Comment by shayne-fletcher-da** [comment]
Can't say off the top of my head. Need to look into it. Thanks for the suggestion!

**Comment by shayne-fletcher-da** [comment]
Related:

> use the language extension PackageImports to do import "ghc-lib" ... or import "ghc-lib-parser" ... as approriate

This turns out to not be such great advice. In HLint for example, we prefer to link GHC actual rather than `ghc-lib-parser` when it's known that the (compiling) compiler is compatible (8.8.1). This trick requires NOT using package imports.
