### ISSUE TITLE
Delete stale branches

### ISSUE THREAD

**Issue by shayne-fletcher** [digital-asset/ghc-lib#174]
I'd like to delete all branches except master listed currently at https://github.com/digital-asset/ghc-lib/branches/all . Before I do, quick check no-one objects?

**Comment by cocreature** [comment]
sounds good :+1:

**Comment by shayne-fletcher-da** [comment]
![Screen Shot 2020-01-16 at 12 03 36 PM](https://user-images.githubusercontent.com/41306216/72546159-45f23480-3858-11ea-8984-97e283752d7f.png)
