### ISSUE TITLE
Examples don't work with their own source code

### ISSUE THREAD

**Issue by arybczak** [digital-asset/ghc-lib#189]
Because their source code has CPP. Is it possible to parse modules that contain CPP with ghc-lib-parser?

**Comment by 524119574** [comment]
Just wondering what is the command that we should use for running the example?
I have tried after running
```
git clone git@github.com:digital-asset/ghc-lib.git
cd ghc-lib
stack runhaskell --package extra --package optparse-applicative CI.hs -- --ghc-flavor=ghc-8.8.1
```
And then

```
runghc examples/mini-hlint/src/Main.hs examples/mini-hlint/test/MiniHlintTest.hs
```

But I am getting the error:
`error: missing binary operator before token "("` on line 12 and line 16.

Any idea on what might be wrong?

**Comment by shayne-fletcher** [comment]
@524119574 You can execute this command after the one you posted above to run that test.
```
stack exec -- mini-hlint examples/mini-hlint/test/MiniHlintTest.hs
```
Alternatively, if you are not interested in building `ghc-lib`, you could,
```
cd ghc-lib/examples/mini-hlint
cabal new-build
cabal new-run mini-hlint -- test/MiniHlintTest.hs
```

**Comment by shayne-fletcher** [comment]
@arybczak It would appear, not with `ghc-lib-parser` alone. It turns out that `compiler/main/DriverPipeline.hs` has the function `doCpp` which would appear to be what's needed but it's in `ghc-lib` not `ghc-lib-parser`. I can look into the feasibility of moving that.

**Comment by shayne-fletcher** [comment]
@524119574 Your `runghc` approach can be made to work like this:
```
runghc --ghc-arg="-package ghc-lib-parser" --ghc-arg="-package extra" --ghc-arg="-package uniplate" examples/mini-hlint/src/Main.hs examples/mini-hlint/test/MiniHlintTest.hs
examples/mini-hlint/test/MiniHlintTest.hs:7:18-28 : lint : double negation `not (not x)'
```
Of course this requires that you have all the packages in your cache. You can achieve that with by running 
```bash
cabal install ghc-lib-parser extra uniplate
```
first.

**Comment by shayne-fletcher** [comment]
@@arybczak Unfortunately, `DriverPipeline` in the 8.8 series does not expose `doCpp`. `GHC.Driver.Pipeline` on HEAD however does expose it so it might be possible to use with 8.10 `ghc-lib`s. Looking further into it.

**Comment by arybczak** [comment]
Thanks for looking into it. I already figured out how to do it though - it's [here](https://github.com/arybczak/ghc-tags/blob/d4b245b31275f3adcfe83900adfdf0ada308be4a/src/Plugin/GhcTags.hs#L107) if you're curious (basically function `preprocess` from `DriverPipeline` does the trick). My package depends on `ghc` at the moment, but changing the dependency to `ghc-lib` works out of the box.
