### ISSUE TITLE
ghc-lib-8.8.3.* base dependency out-of-bounds error with ghc-8.10 

### ISSUE THREAD

**Issue by shayne-fletcher** [digital-asset/ghc-lib#194]
See https://github.com/ndmitchell/hlint/issues/951. ghc-8.8.3.20200224 + cabal 3.2.0.0 + ghc-8.10 produces a configure error because the upper-limit of base is 4.14.

**Comment by shayne-fletcher** [comment]
There is also an issue with ghc-prim. See https://github.com/ndmitchell/hlint/issues/951#issuecomment-612638438. That one could be a little fiddlier.

**Comment by essandess** [comment]
Re: https://github.com/ndmitchell/hlint/issues/951#issuecomment-612641551
> @essandess I'm flying blind since I don't have the capacity to build with 8.10 yet (waiting on a stack resolver). If I were to give you a .tar.gz to test, would you be able to do that?

Possibly. I just bootstrapped ghc 8.10.1 from the prebuilt binary, and am using the prebuilt cabal 3.2.0.0 binary. See source sites in:
* https://github.com/macports/macports-ports/blob/master/lang/ghc/Portfile
* https://github.com/macports/macports-ports/blob/master/lang/cabal/Portfile

Would it possible for you to download these binaries, clone hlint, and run a modified version of this build command?```bash
/opt/local/bin/cabal new-configure --prefix=/opt/local --bindir=/opt/local/bin --libdir=/opt/local/lib --libsubdir=hlint --dynlibdir=/opt/local/lib --libexecdir=/opt/local/libexec --libexecsubdir=hlint --datadir=/opt/local/share/hlint --docdir=/opt/local/share/doc/hlint --htmldir=/opt/local/share/doc/hlint --sysconfdir=/opt/local/etc/hlint --enable-documentation --enable-relocatable
```

**Comment by shayne-fletcher** [comment]
Actually I just got a build of ghc-lib-parser with 8.10 using ghc-prim-6.1 so I think we'll be OK. The fiddliness I was worried about doesn't look like it's going to manifest yet (https://gitlab.haskell.org/ghc/ghc/commit/705a16df02411ec2445c9a254396a93cabe559ef). Just running one more very specific test and if that works out, I'll cut a new ghc-lib-parser.

**Comment by shayne-fletcher** [comment]
@essandess ghc-lib-parser-8.8.3.20200412.1 (https://hackage.haskell.org/package/ghc-lib-parser-8.8.3.20200412) just went to hackage now.
