### ISSUE TITLE
Early warning: New parser dependencies.

### ISSUE THREAD

**Issue by AndreasPK** [digital-asset/ghc-lib#255]
https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4230 will add new modules to GHC. It seems the parser will transitively depend on at least one of them based on the failure of CountParserDeps tests.

I thought it might be useful to report this here early.

**Comment by hurryabit** [comment]
FYI @shayne-fletcher

**Comment by shayne-fletcher** [comment]
Thanks so much @AndreasPK , very nice of you to take the time to share this with us!

**Comment by shayne-fletcher** [comment]
please close @dylant-da @garyverhaegen-da @akrmn @samuel-williams-da
