### ISSUE TITLE
Please normalise filepaths.

### ISSUE THREAD

**Issue by phadej** [digital-asset/ghc-lib#256]
The `ghc-lib-parser` has

```cabal
    hs-source-dirs;
        ...
        compiler/.
        compiler
```

The `Cabal-3.6` will warn on trailing dot paths. 

In fact, the `ghc-lib-parser` is *the only package* having `directory/.` i.e. trailing dot (not counting somewhat common `./.`) , otherwise I'd made parser fail out right on it.
(I still may make it so, have to think).

**Comment by shayne-fletcher** [comment]
Thanks for pointing this out. Fix is on the way!

**Comment by shayne-fletcher** [comment]
Fixed by https://github.com/digital-asset/ghc-lib/pull/257.

**Comment by shayne-fletcher** [comment]
suggest close @dylant-da @garyverhaegen-da @akrmn @samuel-williams-da
