### ISSUE TITLE
Add "cc-options: -DTHREADED_RTS" to ghc-lib-parser.cabal?

### ISSUE THREAD

**Issue by TerrorJack** [digital-asset/ghc-lib#258]
`ghc-lib-parser` contains `genSym.c` which backs `Unique`-related logic in GHC. It uses the `THREADED_RTS` CPP macro in the `genSym` function to guarantee uniqueness when there're multiple runtime capabilities. The GHC make systems add `-optc-DTHREADED_RTS` when building the threaded way of `ghc` to flip on this macro.

Now, since `ghc-lib-parser` doesn't seem to flip on this macro or patch `genSym.c`, this looks like a potential source of heisenbugs given `Unique` related logic is used in a lot of places in `ghc-lib-parser`/`ghc-lib`. We recently started rearchitecting Asterius to use a `ghc-lib`-like ghc api package, and encountered a "duplicate label in graph" error in Cmm related logic, and enabling `-DTHREADED_RTS` solves that error. So might be worth reporting here as well :)

**Comment by shayne-fletcher** [comment]
Actually, ghc-lib-parser.cabal files do define `-DTHREADED_RTS`. I seem to be missing something?

**Comment by TerrorJack** [comment]
Ah, I did a GitHub search of `THREADED_RTS` and found nothing before opening the issue. It seems it's indeed present in the `.cabal` file on Hackage, should have checked there first. Closing this one then.
