### ISSUE TITLE
ghc-lib won't load in ghci on Windows

### ISSUE THREAD

**Issue by ndmitchell** [digital-asset/ghc-lib#27]
Using GHC 8.6.3 64bit on Windows.

```
C:\Neil\ghc-lib\examples\mini-hlint>cabal repl
Preprocessing executable 'mini-hlint' for mini-hlint-0.1.0.0..
GHCi, version 8.6.3: http://www.haskell.org/ghc/  :? for help
ghc.exe:  | C:\Users\ndmit_000\AppData\Roaming\cabal\x86_64-windows-ghc-8.6.3\ghc-lib-0.1.0-5TETMXYBgAD4AgU2Eb8FSv\HSghc-lib-0.1.0-5TETMXYBgAD4AgU2Eb8FSv.o: unknown symbol `keepCAFs'
ghc.exe: unable to load package `ghc-lib-0.1.0'
```

**Comment by shayne-fletcher-da** [comment]
Ack.

**Comment by shayne-fletcher-da** [comment]
ghci loads ok on MacOS but seg-faults running `main`
```
*Main> :main "/Users/shaynefletcher/project/ghc-lib.git/examples/mini-compile/test/MiniCompileTest.hs"
Segmentation fault: 11
```

**Comment by ndmitchell** [comment]
The only thing that references `keepCAFs` is `compiler/ghci/keepCAFsForGHCi.c` which is just a file with a constructor function (run at C library load) which does `keepCAFs = 1`. This is a tweak to tell GHCi not to collect CAFs, which is very important for a `ghci` based on `ghc`. Given we don't have a runtime, this isn't going to be an actual issue.

I don't know how the `GHC` library itself finds the `keepCAFs` symbol - maybe there is a special case somewhere? My obvious attempts like putting the `rts` as a dependency didn't help, but I didn't investigate too hard given the simple solution works well.
