### ISSUE TITLE
Unable to `runGhc` if ghc and ghc-lib versions differ

### ISSUE THREAD

**Issue by zliu41** [digital-asset/ghc-lib#308]
When running the following with a ghc version that doesn't match the ghc-lib version, such as ghc 8.10 and ghc-lib 9.0.1:

```haskell
main :: IO ()
main = GHC.runGhc (Just GHC.Paths.libdir) (pure ())
```

I get

```
*** Exception: Can't parse "/nix/store/2ip3lwzqswai3zz33407h4b2q3har28p-ghc-8.10.4/lib/ghc-8.10.4/platformConstants"
```

Is there a workaround?

**Comment by shayne-fletcher** [comment]
Use the `ghc-lib` data-directory e.g.
```haskell

{-# LANGUAGE PackageImports #-}

module Main where

import "ghc-lib" GHC
import Paths_ghc_lib

import System.FilePath.Posix((</>))

main :: IO ()
main = do
  dir <- getDataDir
  GHC.runGhc (Just dir) (pure ())
  putStrLn $ dir </> "platformConstants" ++ "' loaded."
```

**Comment by zliu41** [comment]
Thanks!

**Comment by zliu41** [comment]
@shayne-fletcher This makes this trivial example work, however, if I do something non-trivial in the ghc monad, such as calling `setSessionDynFlags`, then I get `ghc: can't find a package database at /home/zliu41/.cabal/store/ghc-8.10.4/ghc-lib-9.0.1.20210324-be7c10809cf930930d0c6d30ece348f63b5fe94e9b67434ca837aac34c3ca5bb/share/package.conf.d`. Do you happen to know how to set the correct package db path?

**Comment by zliu41** [comment]
Made it work by doing `setEnv "GHC_PACKAGE_PATH" GHC.Paths.libdir` before calling `runGhc`. If there's a better way please let me know.. :blush:

**Comment by shayne-fletcher** [comment]
while i'm pleased to hear things are working out for you, i think you are testing the limits of what you can do with `ghc-lib`. see the [`README`](https://github.com/digital-asset/ghc-lib#readme) for more details on the limitations of `ghc-lib` with respect to package databases. depending on what you're trying to to, the [`mini-compile`](https://github.com/digital-asset/ghc-lib/blob/master/examples/mini-compile/src/Main.hs) example might help

**Comment by shayne-fletcher** [comment]
also, the discussion in [this ticket](https://github.com/digital-asset/ghc-lib/issues/286) may also be relevant

**Comment by zliu41** [comment]
Thanks @shayne-fletcher . If I understand the README correctly, setting `GHC_PACKAGE_PATH` is a bad idea since there's no guarantee that ghc-lib can work with the package db of a different ghc version.

What I'm trying to do is looking into whether ghc-exactprint can depend on ghc-lib rather than ghc. There are a bunch of internal functions that call `get/setSessionDynFlags`. I'm guessing these can be replaced by passing the `DynFlags` as a parameter, and if so those functions should no longer require the Ghc monad.

**Comment by shayne-fletcher** [comment]
i see that mini-compile does call `setSessionDynFlags` but it does so with a ("faked up") `DynFlags` constructed in such a way that it's understood that there is no package database 

> What I'm trying to do is looking into whether ghc-exactprint can depend on ghc-lib rather than gh

that would be awesome! please keep us posted on your progress!

**Comment by zliu41** [comment]
@shayne-fletcher This doesn't seem likely to be doable since ghc-exactprint relies on `GHC.Driver.Pipeline.preprocess` to preprocess CPP, and I always get "unknown package: rts" when using ghc-lib's `preprocess`. Are you aware of any examples or existing use case of `preprocess` via ghc-lib?

**Comment by shayne-fletcher** [comment]
The discussion in [this issue](https://github.com/digital-asset/ghc-lib/issues/189) suggests that it might be possible.
