### ISSUE TITLE
Clarify scope in synopsis

### ISSUE THREAD

**Issue by andreasabel** [digital-asset/ghc-lib#351]
At https://hackage.haskell.org/package/ghc-lib-parser, the synopsis says:
> A package equivalent to the ghc package, but which can be loaded on many compiler versions.

This seems to promise too much:
- "many" seems to be 3 major versions.
- A more precise description would be: _`ghc-lib-parser-x.y.z.d` can be build with any GHC x.y and the two major versions below it_.  Is that correct?
- So in particular, I cannot build `ghc-lib-parser-x.y.z.d` with any major GHC _above_ x.y?

I am asking because I am l would like to build https://github.com/agda/hs-tags with GHC 9.2 without porting it to the `ghc-9.2` library (and I was hoping your package would allow me to do this).

Suggested action: add to the synposis to make it more precise.

**Comment by andreasabel** [comment]
@shayne-fletcher : Can I get a triage?

**Comment by shayne-fletcher** [comment]
@andreasabel your read sounds about right. ghc-lib is ghc source and subject to the same constraints.

**Comment by andreasabel** [comment]
@shayne-fletcher : Do you want me to submit a PR along the lines above or do the clarification yourself?

**Comment by shayne-fletcher** [comment]
@andreasabel PR welcome.

it seems by the way the [FAQ section](https://github.com/shayne-fletcher/ghc-lib#faq) of the README says something about this (though it could use modernizing).

**Comment by shayne-fletcher** [comment]
related https://github.com/digital-asset/ghc-lib/issues/349. also, https://github.com/digital-asset/ghc/pull/96 is relevant. potentially could make use of these patches if determined to compile an 8.10 ghc-lib-parser with a 9. compiler.
