### ISSUE TITLE
Template Haskell extension

### ISSUE THREAD

**Issue by bubba** [digital-asset/ghc-lib#38]
Is it possible to use the `ghc-lib` Template Haskell with `{-# LANGUAGE TemplateHaskell #-}`? Even with `{-# LANGUAGE RebindableSyntax #-}` names and expressions end up using the types from the `template-haskell` package

**Comment by shayne-fletcher-da** [comment]
AFAIK, this should be fine. `ghc-lib` includes the `template-haskell` library, and a quick smoke test hacking up `examples/mini-hlint/src/Main.hs` to say,
```
{-# LANGUAGE TemplateHaskell #-}
import qualified "ghc-lib" Language.Haskell.TH
...
```
compiles and links ok.

**Comment by bubba** [comment]
With this example in `mini-hlint`:
```haskell
import qualified "ghc-lib" Language.Haskell.TH as A

test :: A.Q [A.Dec]
test = [d|foo = 3|]
```

I end up getting:

```
src/Main.hs:46:8: error:
    • Couldn't match type ‘template-haskell-2.14.0.0:Language.Haskell.TH.Syntax.Q
                             [template-haskell-2.14.0.0:Language.Haskell.TH.Syntax.Dec]’
                     with ‘A.Q [A.Dec]’
      NB: ‘A.Q’
            is defined in ‘Language.Haskell.TH.Syntax’
                in package ‘ghc-lib-0.20190204’
          ‘template-haskell-2.14.0.0:Language.Haskell.TH.Syntax.Q’
            is defined in ‘Language.Haskell.TH.Syntax’
                in package ‘template-haskell-2.14.0.0’
      Expected type: A.Q [A.Dec]
        Actual type: template-haskell-2.14.0.0:Language.Haskell.TH.Lib.Internal.DecsQ
    • In the expression: [d| foo = 3 |]
      In an equation for ‘test’: test = [d| foo = 3 |]
   |
46 | test = [d|foo = 3|]
   |        ^^^^^^^^^^^^
```

**Comment by ndmitchell** [comment]
@bubba can you clarify exactly what you're trying to do?

* Are you trying to run a file with TH through mini-hlint? That should be fine.
* Are you trying to use mini-compile on something with TemplateHaskell? That won't work, as TemplateHaskell causes compile-time evaluation, and ghc-lib isn't capable of doing evaluation as it doesn't have a suitable package database (unless you make one, which is probably far from trivial).
* Are you trying to use mini-compile with rebindable syntax? That should work absolutely fine as it's something I've done.

**Comment by bubba** [comment]
I was trying to do the first case, I realise now that I should have just used standard template-haskell and not ghc-lib's. Thanks for clarifying this

**Comment by ndmitchell** [comment]
Great. I've added a note to the README clarifying where TH will and won't work.
