### ISSUE TITLE
Hackage builds broken

### ISSUE THREAD

**Issue by brandonchinn178** [digital-asset/ghc-lib#407]
Seems like Hackage builds have been broken ever since the `9.2.3.20220709` release:
```
Resolving dependencies...
Starting     ghc-lib-parser-9.2.3.20220709
Building     ghc-lib-parser-9.2.3.20220709
Failed to install ghc-lib-parser-9.2.3.20220709
Build log ( /home/builder/.cabal/logs/ghc-8.10.2/ghc-lib-parser-9.2.3.20220709-3U895tZbJzs3ywTiv6aYte.log ):
cabal: Entering directory '/tmp/cabal-tmp-25311/ghc-lib-parser-9.2.3.20220709'
Configuring ghc-lib-parser-9.2.3.20220709...
Preprocessing library for ghc-lib-parser-9.2.3.20220709..
happy: 1845: unrecognised directive: %shift

cabal: Leaving directory '/tmp/cabal-tmp-25311/ghc-lib-parser-9.2.3.20220709'
cabal: Error: some packages failed to install:
ghc-lib-parser-9.2.3.20220709-3U895tZbJzs3ywTiv6aYte failed during the
building phase. The exception was:
ExitFailure 1
```

This seems to be causing anything depending on `ghc-lib-parser` to also fail builds:
* https://hackage.haskell.org/package/fourmolu-0.8.1.0/reports/2
* https://hackage.haskell.org/package/ormolu-0.5.0.1/reports/2
* https://hackage.haskell.org/package/hlint-3.4.1/reports/2

Probably the cause: https://github.com/haskell/hackage-server/issues/1132. Opening this issue to track it on this end, though

**Comment by shayne-fletcher** [comment]
upgrading happy is the fix isn't it? i appear to be able to download & build the mentioned release from hackage. is this an ongoing issue?

**Comment by brandonchinn178** [comment]
> i appear to be able to download & build the mentioned release from hackage

That's not what I'm talking about; 9.2.3.20220709 still has a build failure and no docs: https://hackage.haskell.org/package/ghc-lib-parser-9.2.3.20220709

But yes, this should be fixed now, since Hackage Server upgraded happy in August. Indeed, all the ghc-lib-parser versions after August 2022 are building fine

**Comment by shayne-fletcher** [comment]
> > i appear to be able to download & build the mentioned release from hackage
> 
> That's not what I'm talking about; 9.2.3.20220709 still has a build failure and no docs: https://hackage.haskell.org/package/ghc-lib-parser-9.2.3.20220709

ah right. sorry i didn't understand. thanks for explaining!
