### ISSUE TITLE
Bump transformers upper bound

### ISSUE THREAD

**Issue by brandonchinn178** [digital-asset/ghc-lib#426]
This causes a rebuild of boot libraries because GHC is now using transformers 0.6: https://github.com/haskell/unix/issues/271#issuecomment-1409061761

**Comment by shayne-fletcher** [comment]
hi @brandonchinn178 , could you elaborate please? what is it exactly you are reporting? what is wrong and if suitable how to reproduce it?

**Comment by brandonchinn178** [comment]
ah never mind. I guess ghc-lib-parser follows GHC versions, so it doesn't make sense for ghc-lib-parser-9.4 to bump bounds to be compatible with GHC 9.6

**Comment by shayne-fletcher** [comment]
quite. ghc-lib-parser-9.4 supports build with compilers in the range [ghc-9.0.1, ghc-9.6.1).
