### ISSUE TITLE
ghc-lib-parser-9.4.4.20221225: building ghc-lib-parser with --ghc-option=-optc-ggdb3 gives "<built-in>:0:2: lexical error"

### ISSUE THREAD

**Issue by noodelhl** [digital-asset/ghc-lib#438]
# Issue Summary

Running the following yields `<built-in>:0:2: lexical error` after build is finished:
```
cabal get ghc-lib-parser
cd ghc-lib-parser...
cabal configure --ghc-option=-optc-ggdb3
cabal build
```

```
[376 of 377] Compiling GHC.Driver.Hooks ( compiler/GHC/Driver/Hooks.hs, /tmp/ghc-lib-parser-9.4.4.20221225/dist-newstyle/build/x86_64-linux/ghc-9.0.2/ghc-lib-parser-9.4.4.20221225/build/GHC/Driver/Hooks.o, /tmp/ghc-lib-parser-9.4.4.20221225/dist-newstyle/build/x86_64-linux/ghc-9.0.2/ghc-lib-parser-9.4.4.20221225/build/GHC/Driver/Hooks.dyn_o )
[377 of 377] Compiling GHC.Driver.Config ( compiler/GHC/Driver/Config.hs, /tmp/ghc-lib-parser-9.4.4.20221225/dist-newstyle/build/x86_64-linux/ghc-9.0.2/ghc-lib-parser-9.4.4.20221225/build/GHC/Driver/Config.o, /tmp/ghc-lib-parser-9.4.4.20221225/dist-newstyle/build/x86_64-linux/ghc-9.0.2/ghc-lib-parser-9.4.4.20221225/build/GHC/Driver/Config.dyn_o )

<built-in>:0:2: error: lexical error
```

[build.log](https://github.com/digital-asset/ghc-lib/files/10835525/build.log) from ```cabal clean; cabal configure --ghc-option=-optc-ggdb3; cabal build```

# Environment
```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.0.2
$ gcc --version
gcc (Gentoo 12.2.1_p20230121-r1 p10) 12.2.1 20230121
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ uname -a
Linux noodelpc 6.1.11-gentoo-x86_64 #1 SMP PREEMPT_DYNAMIC Sat Feb 11 19:40:46 CST 2023 x86_64 AMD Ryzen 7 3700X 8-Core Processor AuthenticAMD GNU/Linux
```

# Expected behavior
Successful build with `--ghc-option=-optc-ggdb3`

**Comment by shayne-fletcher** [comment]
the logs appear to indicate ghc-lib-parser-9.4.4.20221225 rather than ghc-lib-parser-9.2.5. regardless, this is going to be an issue with ghc source. i suggest building ghc itself with the given flag from the ghc-9.4.4-release branch will exhibit the same issue & should it be reproduced then reported on the ghc issue tracker.

**Comment by shayne-fletcher** [comment]
by the way, didn't you mean `--ghc-options=-optc-ggdb3` (plural not singular)? is the issue as simple as that?

**Comment by shayne-fletcher** [comment]
> by the way, didn't you mean `--ghc-options=-optc-ggdb3` (plural not singular)? is the issue as simple as that?

i'm guessing not since in either case it seems to result in writing
```
program-options
  ghc-options: -optc-ggdb3
```
to cabal.project.local

**Comment by shayne-fletcher** [comment]
a couple more data-points:
- was unable to reproduce with ghc-lib-parser-9.4.4.20221225 on my mac
- googling around suggests the error is being issued by cabal itself and that it may relate to locales

hope this helps. do please let us know if/when you get to the bottom of it!

**Comment by noodelhl** [comment]
> the logs appear to indicate ghc-lib-parser-9.4.4.20221225 rather than ghc-lib-parser-9.2.5

Updated the issue title.

> >by the way, didn't you mean --ghc-options=-optc-ggdb3 (plural not singular)? is the issue as simple as that?
>
> i'm guessing not since in either case it seems to result in writing

Right, I meant non-plural `---ghc-option`

> googling around suggests the error is being issued by cabal itself and that it may relate to locales

I did see something on that as well, I'll investigate that further.
I agree about cabal being suspect from seeing said error occur after the build finishes.

I'll look into that further when I free up next.
Thanks for looking into this.

**Comment by noodelhl** [comment]
Not terribly important point, but I did find out why I put 9.2.5.  See: https://github.com/gentoo-haskell/gentoo-haskell/issues/1388.
I was building with 9.2.5 downstream, but with cabal get, I grabbed 9.4.4 without realizing. So I have reproduced it with 9.2.5.20221107.

**Comment by noodelhl** [comment]
I haven't found the time to look into this properly. I find dealing without -optc-ggdb3 to be good enough for me as of now.
