### ISSUE TITLE
`ghc-lib-parser` should depend on `happy >= 1.20`

### ISSUE THREAD

**Issue by michaelpj** [digital-asset/ghc-lib#483]
See https://github.com/haskell/haskell-language-server/issues/3783#issuecomment-1698715597

**Comment by michaelpj** [comment]
Comparing with `lib:ghc`, both the 9.4 and 9.6 series depend on `happy > 1.20`

**Comment by shayne-fletcher** [comment]
sorry i missed this @michaelpj. getting it fixed up now.

**Comment by michaelpj** [comment]
The issue we had seemed to go away so I'm not 10% sure my diagnosis is correct, here!
