### ISSUE TITLE
`ghc-lib-parser-9.8.1.20231009` does not allow `bytestring-0.12`

### ISSUE THREAD

**Issue by amesgen** [digital-asset/ghc-lib#491]
GHC 9.8.1 bundles `bytestring-0.12.0.2` (see [here](https://downloads.haskell.org/ghc/9.8.1/docs/users_guide/9.8.1-notes.html#included-libraries)), but `ghc-lib-parser-9.8.1.20231009` only allows `bytestring >= 0.11.4 && < 0.12`. This seems a bit surprising.

**Comment by shayne-fletcher** [comment]
as @basvangijzel-DA noted, this is fixed by https://github.com/digital-asset/ghc-lib/pull/492

**Comment by amesgen** [comment]
Perfect, thanks for the swift action :heart:
