### ISSUE TITLE
c-sources cannot have cmm files

### ISSUE THREAD

**Issue by Kleidukos** [digital-asset/ghc-lib#495]
'sup, cabal team here.

You have a problem when you generate cabal files: 

```hs
        [ "      c-sources:" ] ++
        indent3 [ "libraries/ghc-heap/cbits/HeapPrim.cmm" ] ++
```

This cannot possibly work, was giving the appearance of normality, but ultimately this is the wrong stanza. [`cmm-sources`](https://cabal.readthedocs.io/en/stable/cabal-package.html#pkg-field-cmm-sources) must be used.

Cheers

**Comment by shayne-fletcher** [comment]
this was in fact updated last month (https://github.com/digital-asset/ghc-lib/pull/492) to read
```
        [ "    if impl(ghc >= 9.2.2) "] ++ -- cabal >= 3.6.0
        [ "      cmm-sources:" ] ++
        indent3 [ "libraries/ghc-heap/cbits/HeapPrim.cmm" ] ++
        [ "    else" ] ++
        [ "      c-sources:" ] ++
        indent3 [ "libraries/ghc-heap/cbits/HeapPrim.cmm" ] ++
```
@Kleidukos  does that look ok?

**Comment by Kleidukos** [comment]
@cho-m Which compiler did you use with ghc-lib-parser-9.8.1.20231009/ghc-lib-parser-9.6.2.20230523 ?

**Comment by shayne-fletcher** [comment]
i see that ghc-9.8.1-9.8.1.20231009 on hackage is still using cabal-version 2.0 and doesn't have that switching logic so that .cmm files are listed in c-sources. i assume this is causing issues - i'll put a new version up!

**Comment by cho-m** [comment]
Confirmed locally that new `ghc-lib-parser-9.8.1.20231121` works with `cabal-install == 3.10.2.1`.

**Comment by shayne-fletcher** [comment]
have pushed ghc-lib-9.8.1.20231121, ghc-lib-9.6.3.20231121 and ghc-lib-9.6.2.20231121 to hackage.

**Comment by shayne-fletcher** [comment]
@garyverhaegen-da i think this issue is good to close now
