### ISSUE TITLE
`ghc-lib.cabal` has source-repository pointing at GHC

### ISSUE THREAD

**Issue by ivan-m** [digital-asset/ghc-lib#52]
Looking at the [version on Hackage](https://hackage.haskell.org/package/ghc-lib-0.20190402/ghc-lib.cabal) you see:

```cabal
source-repository head
    type: git
    location: git://git.haskell.org/ghc.git
```

**Comment by shayne-fletcher-da** [comment]
It's correct that the source repository be the official GHC upstream I think (that's where the source files referenced in the cabal come from). There was something to fix here though (https://github.com/digital-asset/ghc-lib/pull/53).

**Comment by neil-da** [comment]
We can either point at the GHC upstream or the ghc-lib upstream. While I think the GHC upstream is technically correct, I suspect most people actually expect to hit the ghc-lib upstream.

**Comment by shayne-fletcher-da** [comment]
Resolving this by pointing the URI to ghc-lib. Rationale:
  - Seems to better meet user expectations;
  - The 'source-repository' stanza is often used for determining where to go for support.
