### ISSUE TITLE
GitHub actions disabled?

### ISSUE THREAD

**Issue by shayne-fletcher** [digital-asset/ghc-lib#534]
there are a couple of github workflows in the repo but they don't run on push. is this international? some config disabling actions?

@garyverhaegen-da

**Comment by basvangijzel-DA** [comment]
@dylant-da FYI

**Comment by shayne-fletcher** [comment]
with https://github.com/digital-asset/ghc-lib/pull/539 there is now a complete set of builds via github actions available such that if enabled, azure config can be removed and the project would be migrated over.

**Comment by shayne-fletcher** [comment]
also worth noting that github builds take 50% of the azure build time.

**Comment by paulbrauner-da** [comment]
Hi Shayne. Yes, github actions are disabled. We're looking into enabling them but in the meantime we have some questions on #540.

**Comment by shayne-fletcher** [comment]
in https://github.com/digital-asset/ghc-lib/pull/540#issuecomment-2228931663 we talk about how we don't have a `--da` test (da-ghc-8.8.1) workflow. 

if we make the jump to github now as i advocate we'll have to work out how much we care about not having i suspect. personally, i'm ok with it linux + windows for that build is convincing enough to me and if there were going to be problems, with macos DA testing downstream would show it. if on other hand we do care enough we could keep the azure config for this build as long as intel x86_64 machines are provisioned that way there

**Comment by paulbrauner-da** [comment]
Github actions are now enabled, see https://github.com/digital-asset/ghc-lib/pull/540#issuecomment-2233299172.

**Comment by shayne-fletcher** [comment]
not quite. you can see from https://github.com/shayne-fletcher/ghc-lib/actions/runs/9992917978 for example that @nycnewman 's [c8ce1c7](https://github.com/shayne-fletcher/ghc-lib/commit/c8ce1c71d5b9e44a1ddb0e252eb0c5d65a63851d) caused actions to run on my fork but there still appears to be no jobs running on the digital asset repo itself.

**Comment by shayne-fletcher** [comment]
> in [#540 (comment)](https://github.com/digital-asset/ghc-lib/pull/540#issuecomment-2228931663) we talk about how we don't have a `--da` test (da-ghc-8.8.1) workflow.
> 
> if we make the jump to github now as i advocate we'll have to work out how much we care about not having that build signal.
> 
> personally, i'm ok with it. linux + windows for that build is convincing enough for me. if there were going to be problems for DA, downstream testing would quickly show it. if on other hand we do care enough we could just keep the azure config for this one build.
> 
> lastly of course there's no intention to remove support for running the build locally (or on corporate infra) assuming you have a >= 8.4 darwin x86_64 environment so we're not contemplating losing anything with respect to our ability to running it

i have a fix for this. when the repo is fixed such that i can get changes landed again i'll put up a PR.

**Comment by shayne-fletcher** [comment]
> i have a fix for this. when the repo is fixed such that i can get changes landed again i'll put up a PR.

https://github.com/digital-asset/ghc-lib/pull/543
