### ISSUE TITLE
keepCAFsForGHCi causes a duplicate symobl

### ISSUE THREAD

**Issue by abarbu** [digital-asset/ghc-lib#562]
The GHCi defines keepCAFsForGHCi which ghc-lib-parser also pulls in. This leads to a duplicate symbol error in the linker when using ihaskell in some conditions. Like other cbits symbols this should be renamed. I renamed it with objcopy to ghc_lib_parser_keepCAFsForGHCi and everything works correctly.

**Comment by shayne-fletcher** [comment]
any chance you have a repeatable procedure to produce a failure?
