### ISSUE TITLE
ghc-lib-parser fails to build under ghc-9.8.4

### ISSUE THREAD

**Issue by tomjaguarpaw** [digital-asset/ghc-lib#574]
This has blocked a user in practice: https://old.reddit.com/r/haskell/comments/1h5oxcg/do_you_think_haskell_will_become_more_mainstream/m0inl0z/

```
cabal repl -b ghc-lib-parser==9.8.3.20241103 -w ghc-9.8.4
...
[433 of 433] Compiling GHC.Driver.Config.Parser ( compiler/GHC/Driver/Config/Parser.hs, dist/build/GHC/Driver/Config/Parser.o, dist/build/GHC/Driver/Config/Parser.dyn_o )
compiler/cbits/genSym.c: In function ‘ghc_lib_parser_genSym’:

compiler/cbits/genSym.c:21:38: error:
     error: ‘ghc_unique_counter’ undeclared (first use in this function); did you mean ‘ghc_unique_counter64’?
       21 |     HsInt u = atomic_inc((StgWord *)&ghc_unique_counter, ghc_unique_inc) & UNIQUE_MASK;
          |                                      ^~~~~~~~~~~~~~~~~~
          |                                      ghc_unique_counter64
   |
21 |     HsInt u = atomic_inc((StgWord *)&ghc_unique_counter, ghc_unique_inc) & UNIQUE_MASK;
   |                                      ^

compiler/cbits/genSym.c:21:38: error:
     note: each undeclared identifier is reported only once for each function it appears in
   |
21 |     HsInt u = atomic_inc((StgWord *)&ghc_unique_counter, ghc_unique_inc) & UNIQUE_MASK;
   |                                      ^
`gcc' failed in phase `C Compiler'. (Exit code: 1)
Error: cabal: Failed to build ghc-lib-parser-9.8.3.20241103 (which is required
by fake-package-0). See the build log above for details.
```

**Comment by tomjaguarpaw** [comment]
By contrast, ghc-9.8.1 is fine:

```
% cabal repl -b ghc-lib-parser==9.8.3.20241103 -w ghc-9.8.1
...
GHCi, version 9.8.1: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /tmp/cabal-repl.-3697074/setcwd.ghci
ghci> 
```

**Comment by shayne-fletcher** [comment]
i think this has come up in GHC too i.e. can't build ghc-9.8.3 with ghc-9.8.4.

in general it's a rule that older ghc-lib versions can't be built with newer compilers and that includes e.g. a 9.8.3 ghc-lib with a 9.8.4 build compiler (from the [README](https://github.com/digital-asset/ghc-lib): "More precisely, building ghc-lib is the same as bootstrapping GHC. For a given ghc-lib 'flavor' (like --ghc-flavor=ghc-9.6.1), a build GHC can be at most "two versions behind & not newer" (e.g. --ghc-flavor=ghc-9.6.1 ⇒ [ghc-9.2.1, ghc-9.6.2)").

ideally this would manifest as a build plan failure (i.e. i'd adjust base bounds on ghc-lib-parser-9.8.3.20241103 to exclude build compiler 9.8.4) but there was no base version bump in 9.8.4 that i could use to achieve that (that is, 9.8.3 and 9.8.4 can not be disambiguated by the version of base they ship with - 4.19.2.0 if i'm not mistaken) 😔

it's probable i could hack up a new ghc-lib-parser 9.8.3 release to overcome this particular instance but a better option consistent with the above would be upgrading to ghc-lib-parser-9.8.4.20241130. is that feasible?

**Comment by tomjaguarpaw** [comment]
Oh, for some reason the long version number stopped me noticing it was for 9.8.3! I'm not surprised it can't build then.

> there was no base version bump in 9.8.4 that i could use to achieve that (that is, 9.8.3 and 9.8.4 can not be disambiguated by the version of base they ship with

Ah yes, very awkward.

> a better option consistent with the above would be upgrading to ghc-lib-parser-9.8.4.20241130. is that feasible?

That sounds like the right solution. I'm not the one experiencing this problem myself, it was the person in the linked Reddit comment above. I'll feed back to them.

Thanks!

**Comment by shayne-fletcher** [comment]
@tomjaguarpaw this works
```
cabal get hhp-1.0.2
cd hhp-1.0.2
cabal build --constraint='ghc-lib-parser=9.8.4.20241130'
```

**Comment by shayne-fletcher** [comment]
> @tomjaguarpaw this works
> 
> ```
> cabal get hhp-1.0.2
> cd hhp-1.0.2
> cabal build --constraint='ghc-lib-parser=9.8.4.20241130'
> ```

tracing through the deps, i wager that in fact
```
cabal get hhp-1.0.2
cd hhp-1.0.2
cabal update # the package index needs to know about ghc-lib-parser-9.8.4.20241130!
cabal build
```
will work just as well 😁

**Comment by shayne-fletcher** [comment]
> won't it break under 9.8.3, because it will also try to use the latest minor release of `ghc-lib-parser-9.8`, i.e. `ghc-lib-parser-9.8.4.20241130`, because there is no distinguishing bound on `base`?

no, this will work just fine. the cabal solver will arrive at
  - hlint-3.8
    - ghc-lib-parser-9.8.4.20241130
    - ghc-lib-parser-ex-9.8.0.2

and this is a valid build plan because ghc-lib-parser-9.8.4.20241130 is buildable with ghc-9.8.3.

**Comment by tomjaguarpaw** [comment]
Ah, that's good to know, thanks!
